[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
fs_permissions = [
    { access = "read-write", path = "cache"},
    { access = "read", path = ".treb/registry.json"},
    { access = "read", path = "script/networks" },
    { access = "read", path = "./mgps/"}
]

[lint]
ignore = ["**/*"]

[rpc_endpoints]
# vbase = "${TENDERLY_VBASE_RPC_URL}"
# vbase_root = "${TENDERLY_VBASE_ROOT_RPC_URL}"
# vcelo = "${TENDERLY_VCELO_RPC_URL}"
# vcelo_root = "${TENDERLY_VCELO_ROOT_RPC_URL}"
celo = "${CELO_RPC_URL}"
celo_sepolia = "${CELO_SEPOLIA_RPC_URL}"
monad_testnet = "${MONAD_TESTNET_RPC_URL}"
monad = "${MONAD_RPC_URL}"
anvil = "http://localhost:8545"

[etherscan]
# vbase = { key = "${TENDERLY_ACCESS_TOKEN}", chain = 8453, url = "${TENDERLY_VBASE_RPC_URL}/verify/etherscan" }
monad_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 10143, url = "https://api.etherscan.io/v2/api?chain=10143"}
monad = { key = "${ETHERSCAN_API_KEY}", chain = 143, url = "https://api.etherscan.io/v2/api?chain=143"}
# celo_sepolia = { key= "${ETHERSCAN_API_KEY}", chain = 11142220, url = "https://api.etherscan.io/v2/api?chain=11142220" }

[profile.monad-mainnet.treb.senders.deployer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"


[profile.default.treb.senders.deployer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"

[profile.default.treb.senders.reporter]
type = "private_key"
private_key = "${REPORTER_PRIVATE_KEY}"

[profile.virtual.treb.senders.deployer]
type = "safe"
safe = "0x32CB58b145d3f7e28c45cE4B2Cc31fa94248b23F"
signer = "proposer"

[profile.virtual.treb.senders.proposer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"

[profile.throwaway.treb.senders.deployer]
type = "private_key"
private_key = "${DEPLOYER_PRIVATE_KEY}"

[profile.testnet-v3-rc0.treb.senders.multisig]
type = "safe"
safe = "0x58099B74F4ACd642Da77b4B7966b4138ec5Ba458"
signer = "deployer"

[profile.testnet-v2-rc5.treb.senders.governor]
type = "oz_governor"
governor = "0x23173Ac37b8E4e5a60d787aC543B3F51e8f398b4"
timelock = "0x74c44Be99937815173A3C56274331e0A05611e0D"
proposer = "deployer"

[profile.celo.treb.senders.governor]
type = "oz_governor"
governor = "0x47036d78bB3169b4F5560dD77BF93f4412A59852"
timelock = "0x890DB8A597940165901372Dd7DB61C9f246e2147"
proposer = "deployer"
