[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
ffi = true
additional_compiler_profiles = [
    { name = "no-opt", optimizer_runs = 0 },
    { name = "paris", evm_version = "paris" }
]
compilation_restrictions = [
    { paths = "lib/bold/contracts/src/TroveManager.sol", optimizer_runs = 0 },
    { paths = "lib/mento-core/contracts/tokens/StableTokenV3.sol", evm_version = "paris" }
]
fs_permissions = [
    { access = "read-write", path = "cache"},
    { access = "read-write", path = "out/"},
    { access = "read", path = ".treb/registry.json"},
    { access = "read", path = ".treb/addressbook.json"},
    { access = "read", path = "script/config/"},
    { access = "read", path = "mgps/"}
]

[lint]
ignore = ["**/*"]

[rpc_endpoints]
celo = "${CELO_RPC_URL}"
celo_sepolia = "${CELO_SEPOLIA_RPC_URL}"
monad_testnet = "${MONAD_TESTNET_RPC_URL}"
monad = "${MONAD_RPC_URL}"
anvil = "http://localhost:8545"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 10143, url = "https://api.etherscan.io/v2/api?chainid=10143"}
monad = { key = "${ETHERSCAN_API_KEY}", chain = 143, url = "https://api.etherscan.io/v2/api?chainid=143"}
chain-143 = { key = "${ETHERSCAN_API_KEY}", chain = 143, url = "https://api.etherscan.io/v2/api?chainid=143"}
celo = { key = "${ETHERSCAN_API_KEY}", chain = 42220, url = "https://api.etherscan.io/v2/api?chainid=42220" }
# chain-11142220 = { key = "${ETHERSCAN_API_KEY}", chain = 11142220, url = "https://api.etherscan.io/v2/api?chainid=11142220" }
# celo_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11142220, url = "https://api.etherscan.io/v2/api?chainid=11142220" }
